name: Upload Docker Hub

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

env:
  DOCKER_FILE: docker-compose.yml
  VER: ${{ github.ref_name }}

jobs:
  check-build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: docker build
        run: |
          docker build -t ptjkjm1/my-ubuntu:${{ env.VER }} -f my-ubuntu.Dockerfile .
          docker compose -f ${{ env.DOCKER_FILE }} up -d

  push-docker:
    needs: [ check-build-docker ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - run: echo "PUSH ptjkjm1/test:${{ env.VER }}"

      - name: Push / test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./my-ubuntu.Dockerfile
          push: true
          tags: ptjkjm1/test:${{ env.VER }}
